
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/chatdb?useSSL=false
    username: root
    password:
  jpa:
    database: mysql
    #InnoDB
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show_sql: true

jwt:
  secretKey:
  expiration: 3000  #3000?
